### ISSUE TITLE
It would be better to have an organization for ZeroNet.

### ISSUE THREAD

**Issue by zolagonano** [ZeroNetX/ZeroNet#102]
ZeroNet has other things related to it like the ZeroNet's website, ZeroNet's documentations, ZeroNet's Bundle, ZeroTalk, ZeroHello, ZeroMe, ZeroBlog, ZeroMail, etc.

I think it would be better to have a separate organization in GitHub for everything related to ZeroNet.

**Comment by canewsin** [comment]
https://github.com/ZeroNetX is New Organisation for ZeroNet
