### ISSUE TITLE
Fork ZeroNet Sites too

### ISSUE THREAD

**Issue by zolagonano** [ZeroNetX/ZeroNet#107]
ZeroNet sites(like ZeroMe, ZeroHello), zeronet.io, and ZeroNet's documentation need improvements, please fork them too, so we can contribute to them.

**Comment by canewsin** [comment]
Sites:
https://github.com/ZeroNetX/ZeroHello
https://github.com/ZeroNetX/ZeroTalk
https://github.com/ZeroNetX/ZeroBlog
https://github.com/ZeroNetX/ZeroMe
https://github.com/ZeroNetX/ZeroBoard (Want to bring this back, to reduce spam on ZeroTalk like test posts,)
https://github.com/ZeroNetX/ZeroSites

Documentations:
https://github.com/ZeroNetX/Documentation

Distributions : 
https://github.com/ZeroNetX/ZeroNet-win
https://github.com/ZeroNetX/ZeroNet-dist
https://github.com/ZeroNetX/ZeroNet-linux

**Comment by canewsin** [comment]
closing this for now. comment other sites below if any.
