### ISSUE TITLE
ERROR Site:* Save peer error: NOT NULL constraint failed: peer.time_response

### ISSUE THREAD

**Issue by slrslr** [ZeroNetX/ZeroNet#109]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.6. internal 2 4560
  * Operating system: Linux
  * Web browser: FF
  * Tor status: available
  * Opened port: yes
  * Special configuration: multiuser, bootstrapper

#### Steps to reproduce:

Hello, do You also see these errors?
ERROR Site:1TaLkF..jipT Save peer error: NOT NULL constraint failed: peer.time_response

It seems to be triggered by some regular job when sites are checked or something. Show one entry per the zeronet site many entries per second. Causes tens of thousands lines in 48 hours of runtime when having hundreds of sites. Seen also in current ZeronetX enhanced branch.

**Comment by slrslr** [comment]
I no longer see these errors (in enhanced branch). I will inform if it re-appear.

**Comment by slrslr** [comment]
I am again seeing this issue. 30K ERROR lines for like 48 hours runtime
zeronex and also in zeronetx zeronet-enhanced branch. Regarding ZNE, it is reported by "git status", but "git submodule status" no output
```
$ git pull -v
POST git-upload-pack (155 bytes)
From https://github.com/ZeroNetX/ZeroNet
 = [up to date]        zeronet-enhanced -> origin/zeronet-enhanced
 = [up to date]        canewsin-patch-1 -> origin/canewsin-patch-1
 = [up to date]        master           -> origin/master
 = [up to date]        py3              -> origin/py3
 = [up to date]        py3-internal     -> origin/py3-internal
 = [up to date]        py3-latest       -> origin/py3-latest
 = [up to date]        py3-patches      -> origin/py3-patches
```
So i am re-opening...
Should i try something particular?

**Comment by slrslr** [comment]
180 000 of these warnings in just 4 days
Before this bug is fixed, i have this in zeronet.conf
```
log_level = off
console_log_level = INFO
```

**Comment by canewsin** [comment]
didn't see this error till now on network. is this still happening ?

**Comment by slrslr** [comment]
Seems to no longer happen after like 16 hours of runtime. I will re-open in case it will happen again. Thanks.
