### ISSUE TITLE
Is 1Update8crprmciJHwp2WXqkx2c4iYp18 officiel?

### ISSUE THREAD

**Issue by marek22k** [ZeroNetX/ZeroNet#117]
### Discussed in https://github.com/ZeroNetX/ZeroNet/discussions/116

<div type='discussions-op-text'>

<sup>Originally posted by **marek22k** January  1, 2022</sup>
Is http://127.0.0.1:43110/1Update8crprmciJHwp2WXqkx2c4iYp18 officiel from the ZeroNetX Project?
And if so, why can you only download 0.7.5 there and 0.7.6 on GitHub?</div>

Suggestion: Link from the readme file to the link.

**Comment by canewsin** [comment]
Yes Update Site is Official, 0.7.6 is still in beta/internal beta, will be released to Update site soon.
