### ISSUE TITLE
verify error: VerifyError: No rules for this file in ContentManager.py line 1025 > 985 > 82

### ISSUE THREAD

**Issue by rex4539** [ZeroNetX/ZeroNet#122]
`zeronet-enhanced` branch

Thousands of errors like this `Site:1TaLkF..jipT data/users/17u2vBbwR5NAkg6XarzRXdmW1czuFgYMor/content.json: verify error: VerifyError: No rules for this file in ContentManager.py line 1025 > 985 > 82`

**Comment by emdee-net** [comment]
I'm getting this too, and can't understand why. Is it just a warning?
