### ISSUE TITLE
WebSocket handleRequest error: TypeError: stop() got an unexpected keyword argument 'ui_websocket' in UiWebsocket.py line 80 > 216 > 342 > 1204

### ISSUE THREAD

**Issue by rex4539** [ZeroNetX/ZeroNet#124]
`zeronet-enhanced` branch

Error during shutdown from UI button.

`Site:1HELLo..Ri9d WebSocket handleRequest error: TypeError: stop() got an unexpected keyword argument 'ui_websocket' in UiWebsocket.py line 80 > 216 > 342 > 1204`

**Comment by slrslr** [comment]
I have [mentioned this](https://github.com/ZeroNetX/ZeroNet/issues/120#issuecomment-1006976783) also. The reply to my comment was "plugin changes are yet to be merged from ZE version so this error occured while shutting down."

**Comment by canewsin** [comment]
Plugins have some changes now, try and report

**Comment by slrslr** [comment]
If i have updated correctly before 15 minutes

$ git status
On branch zeronet-enhanced

$ git pull
got a few files, now shows: "Already up to date."

then it continue to appear when trying to quit ZN via UI:

```
[21:20:11] Site:1HELLo..Ri9d WebSocket handleRequest error: TypeError: FileServerPlugin.stop() got an unexpected keyword argument 'ui_websocket' in UiWebsocket.py line 80 > 216 > 342 > 1204 
 {"cmd":"response","to":7000,"result":1,"id":1000002}
```
and ZN continue running

**Comment by slrslr** [comment]
still there after [updating before 30 minutes](https://bin.disroot.org/?bbe42a2e08a79197#Gtuce5wrG7w67QFZX4fAGPs6NXqnyZzDHoxE8fC8yJNh):
```
Site:1HELLo..Ri9d WebSocket handleRequest error: TypeError: BroadcastServer.stop() got an unexpected keyword argument 'ui_websocket' in UiWebsocket.py line 80 > 216 > 342 > 1204 > AnnounceLocalPlugin.py line 136 
 {"cmd":"response","to":544,"result":1,"id":1000002}
```

not shutting down
