### ISSUE TITLE
This is not official ZeroNet

### ISSUE THREAD

**Issue by caryoscelus** [ZeroNetX/ZeroNet#129]
Since this information isn't provided by the author of this fork, i have to put it here myself for all the newcomers. [Official ZeroNet](https://github.com/HelloZeroNet/ZeroNet) is dead (or formally in indefinite development limbo) because its author left the project without leaving anyone as maintainer. That eventually produced a number of forks. This, "ZeroNetX", is just one of the forks.

**Comment by canewsin** [comment]
you want me to mention this on ReadMe ?

**Comment by caryoscelus** [comment]
@canewsin are you the same person as pramukesh on 0net? if that's the case i've already wrote what i want in a public discussion there more than a week ago. (if by some chance you're not, please visit the network you're contributing to sometimes)

everyone should understand that me coming here is a last resort; i'm not going to waste any more time pointing out obvious community and courtesy rules

**Comment by RdeWilde** [comment]
This seems very misleading, doesn't feel very safe to use if we're off for this bad start

**Comment by emdee-net** [comment]
@ canewsin I think  it would be good to put it on the README - maybe put a paragraph at the top describing why and the major differences - for example why are there no plugins? 

And then *please* put a fork-specific Changelog like https://github.com/zeronet-enhanced/ZeroNet/tree/massive-rework/ZNE-ChangeLog and keep it up to date. It's already too hard to see the differences between the 4 forks using diff.
