### ISSUE TITLE
WebSocket handleRequest error: TypeError: actionSiteUpdate() got an unexpected keyword argument 'verify_files'

### ISSUE THREAD

**Issue by rex4539** [ZeroNetX/ZeroNet#132]
`py3-internal` branch

Steps:
On any of your connected sites, select "Verify files".

What happened:
```
Site:1HELLo..Ri9d WebSocket handleRequest error: TypeError: actionSiteUpdate() got an unexpected keyword argument 'verify_files' in UiWebsocket.py line 80 > 236 
 {"cmd":"siteUpdate","params":{"address":"17u2fjXwkMKcUJkH9j4kXD2ha9pNsJPn1A","verify_files":true,"since":0},"wrapper_nonce":"c62adfe2905803e9c2896f04d2f340b9598ea5a53d8c1c7291aac30be8ebc0b5","id":12}
```

Expected result:
Files are verified.

**Comment by slrslr** [comment]
Is not appearing when i click "Verify files" @rex4539  try to update enhanced branch and retry, close this?

**Comment by rex4539** [comment]
As it was written in the bug report, this affects `py3-internal` branch.

If you are attempting to do QA, please do it carefully.

**Comment by slrslr** [comment]
> affects `py3-internal` branch

i have [tried to switch to py3-internal](https://bin.disroot.org/?4406649bb633db9b#AvwN9vDz2ypGkH6xmLF9LwDqgf8So6yT52zqinLdPL25) and "Verify files" of a site and getting same error:

```
Site:1HELLo..Ri9d WebSocket handleRequest error: TypeError: UiWebsocket.actionSiteUpdate() got an unexpected keyword argument 'verify_files' in UiWebsocket.py line 80 > 236 
 {"cmd":"siteUpdate","params":{"address":"1N6zp6jCXPBktNMPfe7UJBpQGyfCq7k2M8","verify_files":true,"since":0},"wrapper_nonce":"string-here-anonymized","id":14}
```

@canewsin remove zeronet-enhanced tag as this is py3-internal only issue?
