### ISSUE TITLE
zeronet.dev + .onion shows wrong download links

### ISSUE THREAD

**Issue by slrslr** [ZeroNetX/ZeroNet#133]
Hello,
https://zeronet.dev/
links to https://github.com/ZeroNetX/ZeroNet#user-content-how-to-join which is py3-latest branch where its README.md page links to original ZN packages which does not have V3 onion support.

Correct link should be https://github.com/ZeroNetX/ZeroNet/tree/py3-internal#how-to-join possibly.
Or setting py3-internal as default when visiting https://github.com/ZeroNetX/ZeroNet/

Download links on http://zeronet34m3r5ngdu54uj57dcafpgdjhxsgq5kla5con4qvcmfzpvhad.onion/ was not updated and so it links to original Zeronet (without v3 onion support).

**Comment by canewsin** [comment]
Yeah they are updated on internal branch, will be updated soon. thanks for pointing out.

**Comment by canewsin** [comment]
Fixed in v0.7.6
