### ISSUE TITLE
ConnServer GetFile exception: AttributeError: 'NoneType' object has no attribute 'write' in FileRequest.py line 250 > 46

### ISSUE THREAD

**Issue by slrslr** [ZeroNetX/ZeroNet#136]
Some days back i have seen this on zeronetx enhanced branch:

`[22:33:13] ConnServer GetFile exception: AttributeError: 'NoneType' object has no attribute 'write' in FileRequest.py line 250 > 46 > Connection.py line 599 > <gevent>/_ssl3.py line 537 > ...`

just now after updating 15 minutes back (git pull) i have seen it again:

`[21:14:20] ConnServer GetFile exception: AttributeError: 'NoneType' object has no attribute 'write' in FileRequest.py line 250 > 46 > Connection.py line 599 > <gevent>/_ssl3.py line 537 > ...`

i am unsure which action triggers it

**Comment by canewsin** [comment]
fixed

**Comment by slrslr** [comment]
I have [updated enhanced branch like 30 minutes back](https://bin.disroot.org/?bbe42a2e08a79197#Gtuce5wrG7w67QFZX4fAGPs6NXqnyZzDHoxE8fC8yJNh) and i have seen this error 2 times:

```
ConnServer GetFile exception: AttributeError: 'NoneType' object has no attribute 'write' in FileRequest.py line 250 > 46 > Connection.py line 599 > <gevent>/_ssl3.py line 537 > ...
```

i do not know what triggers it

**Comment by slrslr** [comment]
After running ZN around 16 hours, i no longer see this error. So i will close it now..

**Comment by slrslr** [comment]
It is back:

`ERROR    ConnServer GetFile exception: AttributeError: 'NoneType' object has no attribute 'write' in FileRequest.py line 254 > 46 > Connection.py line 562 > <gevent>/_ssl3.py line 537 > ...`

Can this be related to web browser bug? Restarting browser helps?
Btw. this is zeronetx updated from updater zite. not zeronet-enhanced (as tagged).

**Comment by canewsin** [comment]
closing as stale issue
