### ISSUE TITLE
Download links in latest branch README.md invalid

### ISSUE THREAD

**Issue by slrslr** [ZeroNetX/ZeroNet#137]
Hello the download links in latest branch, README are invalid:
https://github.com/ZeroNetX/ZeroNet/tree/py3-latest#how-to-join

internal branch though has working links:
https://github.com/ZeroNetX/ZeroNet/tree/py3-internal#how-to-join

i do not know if it downloads correct files for the branch though, just to let you know

Other way is to just link to:
https://github.com/ZeroNetX/ZeroNet/releases/latest

**Comment by canewsin** [comment]
`py3-latest` are correct ones, branch needs to be merged to `py3-internal`, I modified those to make it easy for new users who usually lands on `py3-latest` branch.
