### ISSUE TITLE
ZeroNet.sh uses CRLF terminators

### ISSUE THREAD

**Issue by yanmaani** [ZeroNetX/ZeroNet#145]
### Step 1: Please describe your environment

  * ZeroNet version:  v 0.7.6 (4565)
  * Operating system: Debian Linux
  * Web browser: N/A
  * Tor status: N/A
  * Opened port: N/A
  * Special configuration: N/A

### Step 2: Describe the problem:

When I execute `ZeroNet.sh`, I get this error:

```
$ ./ZeroNet.sh --tor 
zsh: ./ZeroNet.sh: bad interpreter: /bin/bash^M: no such file or directory
```

The root cause of this appears to be the CRLF line terminators:
```
$ file ZeroNet.sh
ZeroNet.sh: Bourne-Again shell script, ASCII text executable, with CRLF line terminators
```

If I switch to Unix line terminators, it works, in principle:

```
$ dos2unix ZeroNet.sh 
dos2unix: converting file ZeroNet.sh to Unix format...
$ file ZeroNet.sh
ZeroNet.sh: Bourne-Again shell script, ASCII text executable
$ ./ZeroNet.sh --tor
./ZeroNet.sh: line 12: runtime/bin/python3: Permission denied
```

(This is a different error, and should go in another issue)

#### Steps to reproduce:

  1. `wget https://github.com/ZeroNetX/ZeroNet/releases/download/v0.7.6/ZeroNet-linux.zip`
  2. `unzip ZeroNet-linux.zip`
  3. `cd ./ZeroNet-linux`
  4. `chmod +x ./ZeroNet.sh`
  5. `./ZeroNet.sh`

#### Observed Results:

* Logs are provided above.

#### Expected Results:

* I expected ZeroNet to start.

### Suggested remedy

Save ZeroNet.sh without CRLF line endings

**Comment by nerd36** [comment]
@canewsin 
In Linux run `$ dos2unix ./ZeroNet.sh` before releasing package. You created it in Windows.

**Comment by canewsin** [comment]
@nerd36 @yanmaani fixed
