### ISSUE TITLE
Favorited sites list is empty after update from official v.0.7.1

### ISSUE THREAD

**Issue by defder-su** [ZeroNetX/ZeroNet#149]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.6 (rev4565)
  * Operating system: macOS 10.13
  * Tor status: always
  * Opened port: no

#### Steps to reproduce:

  1. Update client following http://127.0.0.1:43110/15UYrA7aXr2Nto1Gg4yWXpY3EAJwafMTNk/?Topic:1638193961_12sCaEUFqE6g3JrDqmEA8pn9yrgxwkZQMe.
  2. Check Favorited Sites list.

#### Observed Results:

  * It's empty.

#### Expected Results:

  * Favorited sites list should be preserved.

**Comment by defder-su** [comment]
The old favorited sites list is available in the legacy ZeroHello [page](http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D).

**Comment by slrslr** [comment]
> The old favorited sites list is available

thanks, if anyone have long list it may be possible speed up the process by

backup zeronet/data/users.json
open it, find mentioned old zerohello address and below the section:
```
"favorite_sites": {
...
}
```

and copy it to new zerohello site section, quit ZN, save the file

**Comment by defder-su** [comment]
> backup zeronet/data/users.json open it, find mentioned old zerohello address and below the section:
> 
> ```
> "favorite_sites": {
> ...
> }
> ```
> 
> and copy it to new zerohello site section, quit ZN, save the file

It did the trick, thank you.
