### ISSUE TITLE
Mac OS version is broken

### ISSUE THREAD

**Issue by Astrrra** [ZeroNetX/ZeroNet#151]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.6
  * Operating system: Mac OS
  * Web browser: None
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: Mac OS Monterey 

### Step 2: Describe the problem:
Mac OS reports that the app can't be run. chmod +x of the main executable results in a different error (corrupt app), but doesn't help.

#### Steps to reproduce:

  1. Download the latest release on a Mac
  2. Try to run it
  3. Observe the result

#### Observed Results:

  * Error pop up saying that the app can't be run

#### Expected Results:

  * The zeronet app to start

**Comment by Robotizing** [comment]
View logs in Console app, looking something like `denied since it was quarantined by`, and try to download ZeroNet with other apps (browser, unarchiver).
