### ISSUE TITLE
Error pulling top right menu

### ISSUE THREAD

**Issue by FITFC** [ZeroNetX/ZeroNet#160]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.8
  * Operating system: Windows 10
  * Web browser: Microsof Edge
  * Tor status: always
  * Opened port: yes
  * Special configuration: No

### Step 2: Error pulling top right menu

Internal error: KeyError('data/users/content.json'): 'data/users/content.json'
/src/Ui/UiWebsocket.py line 80 > ...

**Comment by slrslr** [comment]
This will not help you likely. But i would try to pull the menu also on other sites. If all sites has same issue. What about downloading zeronet files again. If one site has the issue, what about trashing mentioned .json file and letting the site download it again by reloading page or Check files menu item in three dots menu next to site on ZeroHello.
