### ISSUE TITLE
You should get zeronet to support Monroe coins

### ISSUE THREAD

**Issue by sfsfrgrg** [ZeroNetX/ZeroNet#171]
You should get zeronet to support Monroe coins and accept the sponsorship of Monroe coins

**Comment by sfsfrgrg** [comment]
I'm the owner of Monroe

**Comment by mx5kevin** [comment]
Fees too high, unsuitable for transferring small amounts, unstable manipulated exchange rate 50-70% value loses, slow transfers. Using this system for small amount anonymous transfers are absolute useless system. 

The ZeroNet system are free, the network does not using these scam coins. None of them these coins are suitable even for donations, or sponsoring creators!

**Comment by mx5kevin** [comment]
Monero are exists. Monroe are not, but if I'm wrong it must be a big scam joke to the creator chosed this too similar name. These rubbish scam coins are produced on an assembly line some peoples. And neither is suitable as a means of payment. Or you can't describe the name correctly.

**Comment by zolagonano** [comment]
If you mean like how it supports bitcoin donations(every site address is a bitcoin public key that people can send bitcoins to it) it's just because ZeroNet uses bitcoin's cryptography, and I don't think it's a good idea to use monero's cryptography for site addresses due to **very** long public keys, additional complexities, and breaking the backward compatibility with other/older ZeroNet clients.

**Comment by caryoscelus** [comment]
@zolagonano zeronet-conservancy already supports [monero , bitcoin and custom donations](https://github.com/zeronet-conservancy/zeronet-conservancy/pull/107) , whilest disabling unsafe and unused site public key donation method

**Comment by zolagonano** [comment]
> @zolagonano zeronet-conservancy already supports [monero , bitcoin and custom donations](https://github.com/zeronet-conservancy/zeronet-conservancy/pull/107) , whilest disabling unsafe and unused site public key donation method

Well, that is pretty simple and good actually. but it's not supporting the coins(i mean like how it supports bitcoin donations), it just takes a address from site admin and shows it in sidebar.
