### ISSUE TITLE
It should have more features than just fixing bugs

### ISSUE THREAD

**Issue by sfsfrgrg** [ZeroNetX/ZeroNet#172]
It should have more features than just fixing bugs

**Comment by sfsfrgrg** [comment]
For example: compatible with Freenet  https://freenetproject.org

**Comment by caryoscelus** [comment]
see https://github.com/zeronet-conservancy/zeronet-conservancy for another fork that is (ironically despite the name choice) working on new features

**Comment by yanmaani** [comment]
Compatibility with Freenet seems pointless. If you want Freenet, why not just install Freenet?

Vote to close.

**Comment by canewsin** [comment]
First Priority is New ZeroNetX Engine in Rust.
Will be ready in 1 or 2 months.
https://github.com/canewsin/zeronet-rs
