### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by purplesyringa** [ZeroNetX/ZeroNet#173]
Check [this ZeroTalk thread](http://127.0.0.1:43110/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/?Topic:1653558834_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di/On+ZeroNet+vulnerabilities) for more information. I have already sent you a message on ZeroMail regarding the fix, but if you'd prefer another method of communication, please tell me.

**Comment by canewsin** [comment]
Thanks for reporting. Sent reply for your mail and replied to your thread.
