### ISSUE TITLE
A git checkout of ZeroNetX is not usable

### ISSUE THREAD

**Issue by emdee-net** [ZeroNetX/ZeroNet#182]
A git checkout of ZeroNetX is not usable  - it contains no plugins. Plugins are not extra to ZeroNet as they are required for core functionality getTrackerHandler.

If you want to add extra plugins from another repository the correct way to do it is with submodules (git clone --recurse-submodules). But core functionality should stay with the core code.

**Comment by canewsin** [comment]
ZeroNetX is going to arch towards security even WebSocket connections are made pluggable in rust version. Say someone wants to Publish their Html only App eg: Docs App, they can completely disable JS in Rust version.

**Comment by canewsin** [comment]
Fixed in v0.8.2
