### ISSUE TITLE
this repository violates GPL

### ISSUE THREAD

**Issue by caryoscelus** [ZeroNetX/ZeroNet#183]
the author of this project has been made aware of this inside the 0net a long time ago , so i'm putting this out mostly for information of those who find this project

https://github.com/ZeroNetX/ZeroNet/commit/ac70f83879ae649460be08119b5decaf4b26a09e (fixing important security vulnerability reported by @imachug) was copypasted from https://github.com/zeronet-conservancy/zeronet-conservancy/commit/855b23a84bec65c3dc56954bd69a46e90da805c4 without attribution or reference to where the code is copied from . this is a clear case of GPL violation , which is easy to fix yet the maintainer does nothing to do so

**Comment by canewsin** [comment]
Fixed https://github.com/ZeroNetX/ZeroNet/commit/86109ae4b29d3aab15a08c2b9ab0e1f75ae9dd11

**Comment by caryoscelus** [comment]
@canewsin thanks for fixing in git , however since you also distribute binaries and sources w/o git history , for compliance you also need to reflect changes and their authorship in CHANGELOG

**Comment by caryoscelus** [comment]
any follow up ?
