### ISSUE TITLE
How to install tor manually？？？

### ISSUE THREAD

**Issue by gbaoye** [ZeroNetX/ZeroNet#184]
plz

**Comment by slrslr** [comment]
Using package manager:
`sudo apt install tor -y 2>/dev/null || yum install epel-release -y 2>/dev/null;yum install tor 2>/dev/null;sudo pacman -S tor -v --no-confirm 2>/dev/null`
([source](http://127.0.0.1:43110/1LfvE91ZF18jdG3wW62Dw7NtfTZh737KPL/?Topic:1605116535_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS/), search for "Enable tor")

or https://zeronet.dev/1DeveLopDZL1cHfKi8UXHh2UBEhzH6HhMp/faq/#how-to-use-zeronet-with-tor

or https://www.torproject.org/download/ (depends on your OS that you have not mentioned)
