### ISSUE TITLE
Running a tracker

### ISSUE THREAD

**Issue by qomhmd** [ZeroNetX/ZeroNet#186]
How to create and run a public tracker? I've seen [this repo](https://github.com/ZeroNetJS/zeronet-tracker/) but it doesn't seemingly work.

**Comment by canewsin** [comment]
enable `Bootstrapper Plugin` by renaming `disabled-Bootstrapper` to `Bootstrapper` in plugins dir.

**Comment by qomhmd** [comment]
In this regard, how I can disable the UI? The only things needed for a tracker are the server `IP` and the `fileserver_port`.

**Comment by canewsin** [comment]
You mean completely turn off Ui access ?

**Comment by canewsin** [comment]
comment these lines
https://github.com/ZeroNetX/ZeroNet/blob/fd857985f61d9301c8a1cf75d0eb130daab571d1/src/main.py#L145-L146


replace this line with
https://github.com/ZeroNetX/ZeroNet/blob/fd857985f61d9301c8a1cf75d0eb130daab571d1/src/main.py#L156

`gevent.joinall([gevent.spawn(file_server.start)])`
