### ISSUE TITLE
Increase Big File Plugin from 10MB to 2500 MB because no large files can be downloaded from all the sites 

### ISSUE THREAD

**Issue by mx5kevin** [ZeroNetX/ZeroNet#201]
### Step 1: Please describe your environment

  * ZeroNet version: 0.8.4 (Rev:4620)
  * Operating system: All
  * Web browser: All
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

 1. Open ZeroUp, StorAge etc Zites what include Optional Files.  Right-sided Zeronet icon on top Help distribute added optional files menu Auto download big file size limit are 10MB with which most of the files cannot be downloaded from a website. 

#### Observed Results:

No file larger than 10MB will be downloaded PDF, MP4 video, files are useless. They are inaccessible to the user.

#### Expected Results:

Press Set and Press Download Previous Files Button  it's already too complicated and hidden. With the 10MB limit no one can use it. In the short term, even this small improvement would help a lot.

The repair can be done in a few minutes and I have tested it and worked. The system is unnecessarily over complicated. Who needs full content of a website with a simple change can download files with two clicks. 10MB default setup are a joke in large optional files, 1500MB are a correct setup. This outrageously low value causes problems for many users. Users cannot download any large files larger than 10MB with the current setup. Let's not make life difficult for users and set a fair value. 2500MB  a decent size I tested the code and so on for content creators and users this setup are much more better. Several people have already requested this change.

core\plugins\Bigfile\BigfilePlugin.py

In line 840

From:

`group.add_argument('--autodownload_bigfile_size_limit', help='Also download bigfiles smaller than this limit if help distribute option is checked', default=10, metavar="MB", type=int)`

Change it to:

`group.add_argument('--autodownload_bigfile_size_limit', help='Also download bigfiles smaller than this limit if help distribute option is checked', default=2500, metavar="MB", type=int)`

Change 10 to 2500.

**Comment by canewsin** [comment]
> 1500MB for single site ?

That's too big for a single site, let's say if user has 10 sites with auto download his data will be exhausted for unnecessarily downloads files they might not need, there is proper ZeroFrame API to ask user to increase site_limit(also for BigFile & Optional Files, some are not documented properly).

For custom use case clients, that host single/few sites as you described are different since they target specific domain.

**Comment by mx5kevin** [comment]
> > 1500MB for single site ?
> 
> That's too big for a single site, let's say if user has 10 sites with auto download his data will be exhausted for unnecessarily downloads files they might not need, there is proper ZeroFrame API to ask user to increase site_limit(also for BigFile & Optional Files, some are not documented properly).
> 
> For custom use case clients, that host single/few sites as you described are different since they target specific domain.

The program takes this limit into only for one file Per file/zite. Example if the site contain 2000GB less than 10MB files then all 2000GB download them with the 10MB limit.  There is no function in the program how much total optional file/in a zite the user can download. The 10MB option makes no sense cannot download larger files than 10MB. But with less than 10MB files downloads an unknown amount. Those who need the full content of a website cannot download it. Video and PDF files are not available. It doesn't harm the system a 1500MB setup. A bigger one1920x1080 MP4 video file are close to 1,5GB. The system cannot download a file what larger than 2GB in any way. In single user zites where have no seed buton the one way which entire content can be downloaded. In multiuser zites like ZeroUP with the 10MB limit still download everything the program without limits all the files what are under 10MB. The limit function makes no sense. Dones not do anything else the setup when the user want download a full zite does not get files what larger than 10MB. The system cannot download files larger than 2 GB maximum 1800MB the system can handle it without any problems. The option with 10MB or 1500MB or 1800MB nor does it regulate how much total files are the user are downloading from a zite. It is only regulated by a single file larger than then only that file is not downloaded.

**Comment by mx5kevin** [comment]
This does not solve the problems of the download system, it only alleviates one thing. 

This would be the permanent solution:

https://github.com/ZeroNetX/ZeroNet/issues/142

However, this will not happen in the near future.

**Comment by mx5kevin** [comment]
This does not solve the problems of the download system, it only alleviates one thing. 

This would be the permanent solution:

https://github.com/ZeroNetX/ZeroNet/issues/142

However, this will not happen in the near future.

**Comment by defder-su** [comment]
Indeed, files 10+ MB is practically unusable.
Non-optional: https://github.com/ZeroNetX/ZeroNet/issues/153.
Optional: disappears from the network due to default 10 MB limit.

Also seeing [related post](http://127.0.0.1:43110/1NFjL6KmJYwojYMat8RXCPo2JWMvNzfHAk/?Post:2).

**Comment by defder-su** [comment]
http://127.0.0.1:43110/ThreadIt.bit/?Topic:1667392806_17KQehVm2u5r4GAjqkC3jRcxepzK6ri51W/On+the+Help+distribute+added+optional+files+option+remove+the+10MB+Auto+download+big+file+size+limit+the+option+only+causes+mayor+problems

**Comment by mx5kevin** [comment]
It works perfectly with 2500MB. It would be logical to specify such a limit. I tested the configuration live on several pages and it has only advantages. I don't see any disadvantages that would prevent this from being a default setting. In other forks the setup must be used too in the future. Using the 10MB limit is a huge disadvantage everywhere, blocks the operation of the entire system.

**Comment by mx5kevin** [comment]
Modern 1920X1080p videos, HD Full HD mp4 muvies required this limit per file. The storage capacity of mobile phones is already quite large. This does not cause any problems at all on laptops and desktop PCs. The setting is optional and can be turned off at any time. Modern single user sites can not work without it. On ZeroNet Dashboard files menu besides that, it's a big problem can not add files  using a link. If the seed button are used and the file are not seeded the system does not add the file to the list, and forget it after restart. If simply the user are clicking the file and have seed ideal way after the browser are closed the file are paused.
