### ISSUE TITLE
I'm unable to rejoin ZeroNet.

### ISSUE THREAD

**Issue by styromaniac** [ZeroNetX/ZeroNet#208]
The download links on the GitHub page are broken (by the way) and there are no trackers in a freshly unarchived ZeroNet install, so the Dashboard and the Config page are unreachable. New users are unable to navigate ZeroNet because of this. Yes, I've tried all of the other forks of ZeroNet. Same problem.

Default trackers should be the ones that *you* host.

Syncronite will not be updated until this problem is resolved, since I'm unable to use any version of ZeroNet(X/-Conservancy).

**Comment by canewsin** [comment]
Updated Latest Release with binaries, check now.

**Comment by styromaniac** [comment]
> Updated Latest Release with binaries, check now.

I need a trackers.json filled with some trackers. I don't remember how it's supposed to be formatted. Can you copy your trackers config and paste it here?

**Comment by canewsin** [comment]
@styromaniac trackers are in this file.
https://github.com/ZeroNetX/ZeroNet/blob/py3-latest/trackers.txt

**Comment by styromaniac** [comment]
> @styromaniac trackers are in this file. https://github.com/ZeroNetX/ZeroNet/blob/py3-latest/trackers.txt

Oh. I didn't realize that the Config page is now available. Thank you!
