### ISSUE TITLE
Constantly Crashing After Adding all 43 ZeroMe Hubs from your ZeroMe Hublist

### ISSUE THREAD

**Issue by ghost** [ZeroNetX/ZeroNet#209]
### Step 1: Please describe your environment

  * ZeroNet version: v0.8.5
  * Operating system: Windows
  * Web browser: Chrome

#### Steps to reproduce:

I clicked to add all of the 43 hubs. Then I tried navigating to the Dashboard, and ZeroNetX crashed. After trying to start it back up again several time, it crashes each time.

**Comment by canewsin** [comment]
@krixano
On windows adjusting `max_files_opened` may help, try reducing to `1024`

**Comment by ghost** [comment]
I was able to finally get it to work. I think what I had to do was not add everything at once. I ended up just starting with a fresh instance of ZeroNetX, and then added only a few ZeroMe hubs at a time.

**Comment by canewsin** [comment]
@krixano I had trouble creating KxoID, still managing that?

**Comment by ghost** [comment]
@canewsin I had it up a bit, but took it back down due to spammers creating ids. I am still considering how I can bring it back up in a way that fights against spam.

**Comment by canewsin** [comment]
Added multisign feature to ZNX, may be we can automate that a bit ?
