### ISSUE TITLE
SiteAnnouncer.py - OSError: cannot watch more than 1024 sockets in <core>/src/Site/SiteAnnouncer.py line 201 > ... in mode start

### ISSUE THREAD

**Issue by JohnoCZ** [ZeroNetX/ZeroNet#213]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: Windows
  * Web browser: Brave
  * Tor status: always
  * Opened port: yes
  * Special configuration: none

### Step 2: Describe the problem:
I started working on a custom search engine, but my search engine is not only about links to some websites, it scans the website and gets all texts, which can be useful in searching for the best results. But after getting somewhere over 2000 - 3000 opened websites, my zeronetx client couldn't start. It doesn't matter if the number is 2000 or like my biggest record of 11,100 opened websites, it still crashed after turning off and on.
Error in debug file: 
OSError: cannot watch more than 1024 sockets in <core>/src/Site/SiteAnnouncer.py line 201 > ... in mode start
And after some time (typically over 1 minute), the zeronetx client crash.
To fix that I always need to delete all zeronetx files and unzip the clear installation of zeronet.

#### Steps to reproduce:

  1. open somewhere over 2000 sites
  2. turn off zeronetx
  3. turn it back on and it will stop working

#### Observed Results:

  * What happened? This could be a screenshot, a description, a log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

There are 2 errors in debug.log.... Nothing else but my debug.log has over 165000 lines but it's mostly filled up with these 2 errors, but different trackers or sites.

[2023-06-14 16:14:15,817] WARNING  Site:1EASNB..su6c Tracker udp://moonburrow.club:6969/announce announce failed: OSError: cannot watch more than 1024 sockets in <core>/src/Site/SiteAnnouncer.py line 201 > ... in mode start
[2023-06-14 16:14:15,822] WARNING  Site:1ChKBK..jea6 Tracker http://t.acg.rip:6699/announce announce failed: AnnounceError: No response after 30s in <core>/src/Site/SiteAnnouncer.py line 201 > <core>/plugins/AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 132 in mode start

#### Expected Results:

Well if we want to use zeronet as alternative internet for websites etc. this should be fixed. Because when there will be a good search engine on zeronet witch can work a little bit like the Google search engine, then some users can run over the number of opened websites like me.

**Comment by slrslr** [comment]
When you search that error "cannot watch more than 1024" you can find [the issue on original Zeronet project](https://github.com/HelloZeroNet/ZeroNet/issues/1136), where maintainer applied some fixes, but these should be already in this Zeronetx fork... Maybe also search that error in general along with "Windows" keyword. If there are any MS Windows tweaks which would increase limit on OS level..

Btw. @canewsin to reproduce the issue, you can use [THIS](http://127.0.0.1:43110/1HMLvnRWViMnuvZc5LK4Dm86sZNcSH1jdh/?Topic:1553085871_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS/3212+zeronet+sites) to quickly load thousands of sites.

**Comment by alessiodam** [comment]
I guess why would you open 2K sites??
