### ISSUE TITLE
How to launch a Zeronet proxy?

### ISSUE THREAD

**Issue by Monoloshka** [ZeroNetX/ZeroNet#232]
How to launch a Zeronet proxy? The best is a transparent proxy but if transparent is not possible then at least http tunnel or socks proxy or any other proxy

**Comment by slrslr** [comment]
Install Zeronet and read these pages:
http://127.0.0.1:43110/138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/?Page:proxies
http://127.0.0.1:43110/1LfvE91ZF18jdG3wW62Dw7NtfTZh737KPL/?Topic:1605116535_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS/

**Comment by Monoloshka** [comment]
> Install Zeronet and read these pages: http://127.0.0.1:43110/138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/?Page:proxies http://127.0.0.1:43110/1LfvE91ZF18jdG3wW62Dw7NtfTZh737KPL/?Topic:1605116535_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS/

I didn't find an answer to my question there

**Comment by Monoloshka** [comment]
What is this mention of transparent proxies?: https://github.com/HelloZeroNet/ZeroNet/releases/tag/v0.6.3

**Comment by slrslr** [comment]
I guess that it is the thing I have linked to, but IMBW.

**Comment by Monoloshka** [comment]
I am currently trying to write code in python using neural networks (Ai). The current code and previously other codes created by neural networks (Ai) opens my site or any other site running on http in .bit without any problem, but if it is a zeronet server, nothing loads. And I can't solve this mystery. `import socket
import threading
import requests
from flask import Flask, request, Response

HOST = '192.168.1.1'
PORT = 8833

SUPPORTED_ZONES = ['.bit', '.yo', '.yu', '.of', '.inf', '.zn', '.list']

app = Flask(__name__)

@app.route('/')
def handle_request():
    try:
        host = request.headers.get('Host')
        if host and any(zone in host for zone in SUPPORTED_ZONES):
            url_to_duplicate = f"http://192.168.1.1:43110{request.path}"
            response = requests.get(url_to_duplicate)
            return Response(response.content, status=response.status_code, content_type=response.headers.get('Content-Type', 'text/html'))
        else:
            return "400 - Bed request", 400
    except requests.RequestException as e:
        return f"Error during a request to the server: {str(e)}", 500
    except Exception as e:
        return f"Internal server error: {str(e)}", 500

if __name__ == "__main__":
    app.run(host=HOST, port=PORT, threaded=True)`

**Comment by Monoloshka** [comment]
Port 43110 is the proxy. I can't open http://zero/ via proxy: Server error
Err: gaierror: [Errno -2] Name does not resolve in UiServer.py line 108 > UiRequest.py line 116 > <gevent>/_socketcommon.py line 190 > ....

**Comment by Monoloshka** [comment]
How to solve the problem? ![image](https://github.com/user-attachments/assets/260bc58c-4a62-4f5b-97a2-df67ef4b49d5)

**Comment by slrslr** [comment]
Do not use .bit domains, these are single point of failure, use zeronet addresses instead: http://127.0.0.1:43110/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT
Also possibly you are using wrong address, it should have been prefixed with "http://127.0.0.1:43110/" or "http://yourzeronetserverIP:43110/"

**Comment by Monoloshka** [comment]
And the domain zone .bit for what then need I do not understand if it can not be normally used like all normal sites?

**Comment by slrslr** [comment]
[.bit may work](http://127.0.0.1:43110/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/?Topic:1516098717_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS), but you forgot that prefix as I have mentioned in my previous post.

a) http://127.0.0.1:43110/Talk.ZeroNetwork.bit
b) http://yourZNinstanceIP:8080/Talk.ZeroNetwork.bit # if 8080 is ui_port defined possibly in zeronet.conf or as a command parameter.

**Comment by Monoloshka** [comment]
Now another question. Is there any way to make it so that a transparent proxy can be routed to an http tunnel in OpenWRT?

**Comment by Monoloshka** [comment]
Problem solved. You should have written in /etc/config/firewall: `config redirect
	option dest 'lan'
	option target 'DNAT'
	option name 'Zeronet'
	option family 'ipv4'
	option src 'lan'
	option src_dip '10.253.0.4'
	option src_dport '80'
	option dest_ip '192.168.2.1'
	option dest_port '43110'

config redirect
	option dest 'lan'
	option target 'DNAT'
	option name 'Zeronet-zone'
	option family 'ipv4'
	option src 'lan'
	option src_dip '10.253.0.5'
	option src_dport '80'
	option dest_ip '192.168.2.1'
	option dest_port '3128'
`  In /etc/dnsmasq.conf write: `address=/bit/10.253.0.5
address=/yo/10.253.0.5
address=/yu/10.253.0.5
address=/of/10.253.0.5
address=/inf/10.253.0.5
address=/zn/10.253.0.5
address=/list/10.253.0.5
address=/zeronet.local/10.253.0.4` Install Squid. In /tmp/squid/squid/squid.conf and /var/squid/squid.conf write: `cache_peer 192.168.2.1 parent 43110 0 no-query no-digest
never_direct allow all
cache_dir null /tmp
access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
http_access allow all
http_access deny all
reply_header_access X-Frame-Options allow all
reply_header_access Content-Security-Policy allow all
reply_header_access Cache-Control allow all
reply_header_access Content-Type allow all
http_port 192.168.2.1:3128 intercept
coredump_dir /tmp/squid
visible_hostname OpenWrt
pinger_enable off
mime_table /tmp/squid/mime.conf
`  Create the files /tmp/log/squid/access.log and /tmp/log/squid/cache.log and access them via WinSCP. In SSH, I made the launch command: Python zeronet.py --ui_host zeronet.local

**Comment by Monoloshka** [comment]
Problem solved. You should have written in /etc/config/firewall: `config redirect
	option dest 'lan'
	option target 'DNAT'
	option name 'Zeronet'
	option family 'ipv4'
	option src 'lan'
	option src_dip '10.253.0.4'
	option src_dport '80'
	option dest_ip '192.168.2.1'
	option dest_port '43110'

config redirect
	option dest 'lan'
	option target 'DNAT'
	option name 'Zeronet-zone'
	option family 'ipv4'
	option src 'lan'
	option src_dip '10.253.0.5'
	option src_dport '80'
	option dest_ip '192.168.2.1'
	option dest_port '3128'
`  In /etc/dnsmasq.conf write: `address=/bit/10.253.0.5
address=/yo/10.253.0.5
address=/yu/10.253.0.5
address=/of/10.253.0.5
address=/inf/10.253.0.5
address=/zn/10.253.0.5
address=/list/10.253.0.5
address=/zeronet.local/10.253.0.4` Install Squid. In /tmp/squid/squid/squid.conf and /var/squid/squid.conf write: `cache_peer 192.168.2.1 parent 43110 0 no-query no-digest
never_direct allow all
cache_dir null /tmp
access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
http_access allow all
http_access deny all
reply_header_access X-Frame-Options allow all
reply_header_access Content-Security-Policy allow all
reply_header_access Cache-Control allow all
reply_header_access Content-Type allow all
http_port 192.168.2.1:3128 intercept
coredump_dir /tmp/squid
visible_hostname OpenWrt
pinger_enable off
mime_table /tmp/squid/mime.conf
`  Create the files /tmp/log/squid/access.log and /tmp/log/squid/cache.log and access them via WinSCP. In SSH, I made the launch command: Python zeronet.py --ui_host zeronet.local

**Comment by Monoloshka** [comment]
![image](https://github.com/user-attachments/assets/1daf53a9-7b64-4822-b4d2-63bce8ddc2f9)
